site_name: akM - Documentation
site_url: https://contactlaplanque.github.io/akM

theme:
  name: material
  language: fr
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: fontawesome/solid/screwdriver-wrench
  palette: 
    scheme: default
    primary: black
    accent: light green
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate 
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate

repo_url: https://github.com/contactlaplanque/akM
repo_name: akM

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
      - icon: fontawesome/brands/instagram 
        link: https://www.instagram.com/contact.laplanque/
      - icon: fontawesome/solid/link
        link: https://laplanque.eu/
  version:
    provider: mike
  generator: false

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: akM - Documentation &copy; 2024 par Association laplanque est publié sous la license CC BY-NC-SA 4.0 

nav:
  - Home: index.md
  - Introduction:
    - À propos de cette documentation: intro/about-these-docs.md
    - Structure du projet akM: intro/project-structure.md
  - Hardware: 
    - Architecture Matérielle: hardware/akM-hardware-architecture.md
  - Software: 
    - Architecture Logicielle: software/akM-software-architecture.md
    - Installation:
      - Avant de commencer: software/installation/requirements.md
      - Guide d'installation: software/installation/step-by-step-guide.md
      - Vérifier votre installation: software/installation/verifying-your-install.md
    - Utilisation:
      - Interface: software/usage/GUI.md
      - Guide de démarrage: software/usage/how-to-start.md
      - Guide d'utilisation: software/usage/how-to-use.md
